name: Release Action on new Git Tags

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release to GitHub Actions
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          version: 16
      - uses: technote-space/release-github-actions@v7
        with:
          CLEAN_TARGETS: '.[!.]*,__tests__,docs,src,*.js,*.ts,*.json,*.lock,*.yml,*.yaml,LICENSE,README,dist'
          DELETE_NODE_MODULES: true
